### ISSUE TITLE
Make severity level of rules configurable

### ISSUE THREAD

**Issue by lucasdinonolte** [lnolte/staticlint#4]
With other linters (like `eslint`) you can set the *severity* or *log level* of rules in the configuration. Something similar for staticlint could be handy.

```javascript
rules: [{
   // Rule violation will output an error
   'html.favicon': 'error',
   // Rule violation will output a warning
   'html.lang': 'warning',
   // Rule will be skipped
   'html.maxOutboundLinks': false, 
}]
```

## Todo
- [ ] refactor config to accept an object of rules and their severity
- [ ] refactor rules, so they only test one thing and one thing only, so it makes sense to set their severity
- [ ] provide a recommended config that will be used as a default

## Ideas
- Allow users to override the default config's rules

**Comment by lucasdinonolte** [comment]
Fixed by #5
